# Copyright (c) 2022 Contributors to the Suwayomi project
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: gh-Pages

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Recreating the project
      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter gen-l10n
      - run: dart run build_runner build --delete-conflicting-outputs
      
      # Build web
      - name: Build Web
        run: flutter build web --release --web-renderer canvaskit --base-href /Tachidesk-Sorayomi/
      
      # Create gh-pages branch if it doesn't exist
      - name: Create & Push gh-pages branch
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout --orphan gh-pages || git checkout gh-pages
          git rm -rf . || true
          cp -R build/web/* .
          touch .nojekyll
          git add .
          git commit -m "Deploy web app to GitHub Pages"
          git push origin gh-pages --force
